name: hsfixit-types
version: 0.0.0
synopsis: Type definitions for the hsfixit fixer
dependencies:
  - base >= 4.9 && <5
  - aeson

library:
  source-dirs: src

_common: !include '../hpack-common/flags.yaml'
