_common/flags: !include '../hpack-common/flags.yaml'

name: hsfixit-types
version: 0.0.0
synopsis: Type definitions for the hsfixit fixer
dependencies:
  - base >= 4.9 && <5
  - aeson
  - text
  - classy-prelude
  - mono-traversable
  - bytestring

library:
  source-dirs: src

<<: *flags

